AllCops:
  TargetRubyVersion: 3.1.x
  NewCops: enable
  Exclude:
    - "test/*"
    - "test/**/*"
    - "db/seeds.rb"
    - "db/schema.rb"
    - "Gemfile"
    - "lib/tasks/*.rake"
    - "bin/*"
    - "config/*"
    - "config/**/*"
    - "spec/spec_helper.rb"
    - "db/migrate/*.rb"
    - Rakefile
    - config.ru
Style/Documentation:
  Enabled: false

# Metrics/MethodLength:
#   Enabled: false

# Metrics/AbcSize:
#   Enabled: false