# frozen_string_literal: true

require 'rails_helper'

RSpec.describe UrlShortening, type: :model do
  it 'is invalid if does not have a original url' do
    url_shortening = UrlShortening.new({})

    expect(url_shortening.valid?).to be(false)
  end

  it 'raise a validation error if does not have a original url' do
    url_shortening = UrlShortening.create({})
    expect(url_shortening.errors.messages).to eq({:original_url=>["can't be blank"]})
  end

  it 'the code is auto generated by callbacks' do
    url_shortening = UrlShortening.create({original_url: 'http://example.com'})
    expect(url_shortening.code).not_to be_nil
  end
end
